name: 'Ruby test'

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
        env:
          BUNDLE_GEMFILE: Gemfile
          
      - name: Test different Bundler versions
        run: |
          for version in 2.5.20 2.5.19 2.5.18 2.5.17 2.5.16; do
            echo "Installing Bundler $version"
            gem install bundler -v $version
            echo "Running bundle install with Bundler $version"
            bundle install
          done
        shell: bash
