name: Check Ruby Version

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-ruby-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch Ruby version from Ubuntu Packages
        run: |
          RUBY_PAGE=$(curl -s https://packages.ubuntu.com/24/ruby)
          RUBY_VERSION=$(echo "$RUBY_PAGE" | grep -oP 'Version: \K[0-9.]+')
          echo "Ruby version available in Ubuntu 24: $RUBY_VERSION"

      - name: Display Ruby version
        run: |
          echo "The available Ruby version is: $RUBY_VERSION"
