name: Testing vcpkg env var in gha

on: push

jobs:
  testing-vcpkg:
    runs-on: ubuntu-24.04  # Change to Ubuntu 24.04
    steps:
      - name: Check vcpkg env var in gha
        run: |
          echo $VCPKG_INSTALLATION_ROOT

  testing-vcpkg-latest:
    runs-on: ubuntu-latest  # Change to the latest Ubuntu
    steps:
      - name: Check vcpkg env var in gha
        run: |
          echo $VCPKG_INSTALLATION_ROOT
