name: Install Clang 18

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clang 18
        run: |
          sudo apt update
          sudo apt install -y wget lsb-release software-properties-common
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-18 main" | sudo tee /etc/apt/sources.list.d/llvm.list
          sudo apt update
          sudo apt install -y clang-18 lld-18 lldb-18

      - name: Set Clang 18 as Default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
          clang --version

      - name: Verify Installation
        run: |
          clang --version
