name: MSSQL Container Debug

on: [push, pull_request]

jobs:
  debug-mssql-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug MSSQL Container Start
        run: |
          docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong!Passw0rd' --name mssql --detach mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
          sleep 120
          docker ps
          docker logs mssql
