name: Install PostgreSQL 13 on Ubuntu 22.04

on:
  push

jobs:
  install_postgresql:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update and install PostgreSQL 15
      run: |
        sudo apt update
        sudo apt install -y postgresql-15
        sudo systemctl start postgresql
        sudo systemctl enable postgresql

    - name: Verify PostgreSQL installation
      run: |
        psql --version
        sudo systemctl status postgresql
