name: Debug
on:
  push

jobs:
  not_working:
    runs-on: ubuntu-24.04
    container:
      image: python:3.10-slim
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install libc6-dev
        run: |
          apt update
          apt install -y libc6-dev
      - run: python
