
name: Check Environment and Runner Info

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check Ubuntu version
        run: lsb_release -a

      - name: Check architecture
        run: uname -m

      - name: Check git version
        run: git --version

      - name: Check environment variables
        run: printenv | grep -i 'runner'

      - name: Enable Debugging
        run: |
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

      - name: Check apt logs
        run: cat /var/log/apt/history.log || echo "No apt history logs found"
