name: Build Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install 7-Zip
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
          choco install 7zip -y

      - name: Download MinGW
        run: |
          $url = "https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-posix/dwarf/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z/download"
          $output = "mingw.7z"
          $client = New-Object System.Net.WebClient
          $client.DownloadFile($url, $output)

      - name: Validate Download
        run: |
          if (-Not (Test-Path "mingw.7z")) {
            Write-Error "Download failed or file not found!"
            exit 1
          }

      - name: Extract 7z File
        run: |
          & 'C:\Program Files\7-Zip\7z.exe' x mingw.7z -o'output_directory'

      - name: Calculate SHA-256 Checksum
        run: |
          Get-FileHash -Path 'output_directory\bin\mingw32-make.exe' -Algorithm SHA256 | Format-List
