name: Download and Verify MinGW

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download MinGW
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-posix/dwarf/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z/download" -OutFile "mingw.7z"
          # Rename the downloaded file to match the expected name
          Rename-Item -Path "mingw.7z" -NewName "i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z"

      - name: Install 7z
        run: |
          choco install 7zip

      - name: Extract MinGW
        run: |
          & "C:\Program Files\7-Zip\7z.exe" x "i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z" -o"mingw"

      - name: Compute SHA256
        run: |
          $filePath = "mingw\i686-8.1.0-release-posix-dwarf-rt_v6-rev0\bin\mingw32-make.exe"
          $hash = Get-FileHash -Path $filePath -Algorithm SHA256
          $hash.Hash.ToLower() | Out-File -FilePath hash.txt -Encoding utf8

      - name: Display SHA256
        run: |
          Get-Content hash.txt
