name: Download and Verify MinGW-w64

on: [push]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install 7-Zip
      run: |
        $url = "https://www.7-zip.org/a/7z1900-x64.exe"
        $output = "$env:TEMP\7z.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList "/S" -Wait

    - name: Download MinGW-w64
      run: |
        $downloadUrl = "https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/8.1.0/threads-posix/dwarf/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z/download"
        $downloadPath = "$env:TEMP\mingw-w64.7z"
        Invoke-WebRequest -Uri $downloadUrl -OutFile $downloadPath

    - name: Extract MinGW-w64
      run: |
        & "$env:ProgramFiles\7-Zip\7z.exe" x "$env:TEMP\mingw-w64.7z" -o"$env:TEMP\mingw-w64"

    - name: Calculate SHA256 for mingw32-make.exe
      run: |
        $mingwMakePath = "$env:TEMP\mingw-w64\bin\mingw32-make.exe"
        if (Test-Path $mingwMakePath) {
            $sha256 = Get-FileHash -Path $mingwMakePath -Algorithm SHA256
            Write-Host "SHA256 for mingw32-make.exe: $($sha256.Hash)"
        } else {
            Write-Error "Error: mingw32-make.exe not found!"
            exit 1
        }

    - name: Cleanup
      run: |
        Remove-Item "$env:TEMP\7z.exe" -Force
        Remove-Item "$env:TEMP\mingw-w64.7z" -Force
