name: Node.js CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the version of Node.js you want to use

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm run package.json # Replace 'your-script' with the actual script name from your package.json
