name: Ruby Gem Workflow

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Check Ruby version
        run: ruby -v

      - name: Check Bundler version
        run: bundle -v

      - name: List gems
        run: gem list
