name: Get File Thumbprint

on:
  workflow_dispatch:

jobs:
  thumbprint:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download Visual Studio Installer
      run: Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_Enterprise.exe -OutFile vs_Enterprise.exe
      shell: pwsh

    - name: Get Signature Thumbprint
      id: get_thumbprint
      run: |
        $filePath = "vs_Enterprise.exe"
        $sig = Get-AuthenticodeSignature -FilePath $filePath
        $thumbprint = $sig.SignerCertificate.Thumbprint
        Write-Output "Signature Thumbprint: $thumbprint"
        echo "thumbprint=$thumbprint" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Output Thumbprint
      run: |
        echo "Signature Thumbprint: $env:thumbprint"
