name: Test VCToolsRedistDir

on:
  push

jobs:
  test:
    runs-on: windows-2019
    steps:
      - name: Set VCToolsRedistDir
        shell: cmd
        run: echo "VCToolsRedistDir=C:\Path\To\VCToolsRedist" >> $GITHUB_ENV

      - name: Check if VCToolsRedistDir exists
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          :: Check if VCToolsRedistDir is set
          if not defined VCToolsRedistDir (
            echo Error: Environment variable VCToolsRedistDir is not set.
            exit /b 1
          )
